AWSTemplateFormatVersion: '2010-09-09'
Resources:
  #logical ID：テンプレート内で一意なID。
  FirstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: first-VPC
